services:
  hugo:
    image: klakegg/hugo:latest
    container_name: hugo
    volumes:
      - .:/src
      - ./public/:/src/public
    restart: always
    command: --watch
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - ./public:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - hugo
    restart: always
  cusdis:
    image: lukaselias/cusdis-arm:latest
    container_name: cusdis
    env_file: 
      - secrets.env
    ports:
      - "3000:3000"
    volumes:
      - ./cusdis_data:/data
    restart: always
