baseURL = 'https://lukaselias.lundmajland.dk'
languageCode = 'en-us'
title = 'Lukas Elias The Developer'

enableRobotsTXT = true

summaryLength = 5

[[menu.main]]
	name = 'Home'
	url = '/'
	weight = 1
[[menu.main]]
	name = 'Devlogs'
	url = '/devlogs'
	weight = 2
[[menu.main]]
	name = 'About'
	url = '/about'
	weight = 3

[[menu.footer]]
	name = 'Email'
	url = 'mailto:lukaslundmajland@gmail.com'
	weight = 1
[[menu.footer]]
	name = 'GitHub'
	url = 'https://github.com/lukaselias'
	weight = 2
[[menu.footer]]
	name = 'tetr.io'
	url = 'https://ch.tetr.io/u/lion_lukas'
	weight = 3
[[menu.footer]]
	name = 'Codepen'
	url = 'https://codepen.io/LukasElias'
	weight = 4
[[menu.footer]]
	name = 'Codepen'
	url = 'https://codepen.io/LukasElias'
	weight = 5
