baseURL = 'https://example.com'
languageCode = 'en-us'
title = 'Lukas Elias The Developer'

summaryLength = 20

[[menu.main]]
	name = 'Home'
	url = '/'
	weight = 1
[[menu.main]]
	name = 'Devlogs'
	url = '/devlogs'
	weight = 2
